---
#Use with --ask-pass
- hosts: servers
  tasks:
  - name: Set authorized key taken from file
    authorized_key:
      user: student
      state: present
      key: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"