---
- name: Checking Gluster packages are installed
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - centos-release-gluster
      - glusterfs 
      - glusterfs-cli 
      - glusterfs-libs 
      - glusterfs-server

# Filesystem creation tasks
- name: Create xfs filesystem
  become: true
  filesystem:
    fstype: xfs
    dev: "{{item}}" 
  with_items:
    - "/dev/sdb"
- name: Create directory to mount filesystem on
  become: true
  file:
    path: "{{item}}" 
    state: directory
  with_items:
    - "/data/openshift"
- name: Mount filesystem
  become: true
  mount:
    path: "/data/openshift"
    src: /dev/sdb
    fstype: xfs
    opts: defaults
    state: present
- name: Create brick directory
  become: true
  file:
    path: "{{item}}" 
    state: directory
  with_items:
    - "/data/openshift/brick"
- import_tasks: gluster-tasks.yml
  when: apply_gluster_role == true