---
- name: Checking Gluster packages are installed
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - centos-release-gluster
      - glusterfs 
      - glusterfs-cli 
      - glusterfs-libs 
      # - glusterfs-server

- name: Set SELinux policies for GlusterFS
  become: true
  command: "{{ item }}"
  with_items:
    - "setsebool -P virt_sandbox_use_fusefs on"
    - "setsebool -P virt_use_fusefs on"
  
- name: Open GlusterFS Ports
  firewalld:
      state: enabled
      zone: public
      immediate: yes
      permanent: yes
      port: "{{ item }}"
  become: true
  loop:
    - "24007/tcp"       #GlusterFS Daemon
    - "24008/tcp"       #GlusterFS Management
    - "49152-49154/tcp" #Gluster brick ports

- name: Install Heketi on master
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - heketi
      - heketi-client
  delegate_to: os1.lab.local
  run_once: true

- name: Copy SSH key to Heketi directory
  become: true
  copy:
    dest: /etc/heketi/heketi_key
    src: /home/student/.ssh/id_rsa.pub
  delegate_to: os1.lab.local
  run_once: true

# Filesystem creation tasks
- name: Create xfs filesystem
  become: true
  filesystem:
    fstype: xfs
    dev: "{{item}}" 
  with_items:
    - "/dev/sdb"
  when: gluster_create_filesystem == true
- name: Create directory to mount filesystem on
  become: true
  file:
    path: "{{item}}" 
    state: directory
  with_items:
    - "/data/openshift"
  when: gluster_create_filesystem == true
- name: Mount filesystem
  become: true
  mount:
    path: "/data/openshift"
    src: /dev/sdb
    fstype: xfs
    opts: defaults
    state: present
  when: gluster_create_filesystem == true
- name: Create brick directory
  become: true
  file:
    path: "{{item}}" 
    state: directory
  with_items:
    - "/data/openshift/brick"
  when: apply_gluster_role == true and gluster_create_filesystem == true
- import_tasks: gluster-tasks.yml
  when: apply_gluster_role == true and gluster_create_filesystem == true