---
# gluster volume
gluster_cluster_hosts: "{{ groups['gluster_servers'] }}"
# gluster_cluster_hosts: 
#   - 192.168.206.72 #os1
#   - 192.168.206.71 #os2
#   - 192.168.206.73 #os3
gluster_cluster_volume: openshift_vol
gluster_cluster_transport: 'tcp'
gluster_cluster_force: 'yes'
gluster_cluster_bricks: '/data/openshift'

# variables to create specific type of the volume
gluster_cluster_replica_count: 3
gluster_cluster_arbiter_count: 1

# variables to set specific volume options
gluster_cluster_options: 'performance.cache-size:256MB'
