apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-consumption
spec:
  hard:
    persistentvolumeclaims: "10" 
    requests.storage: "1Gi" 
    gold.storageclass.storage.k8s.io/requests.storage: "1Gi" 
    silver.storageclass.storage.k8s.io/requests.storage: "1Gi" 
    silver.storageclass.storage.k8s.io/persistentvolumeclaims: "10" 
    bronze.storageclass.storage.k8s.io/requests.storage: "10" 
    bronze.storageclass.storage.k8s.io/persistentvolumeclaims: "1Gi" 
