---
# - name: Stop and disable firewalld
#   become: true
#   service:
#     name: firewalld
#     state: stopped
#     enabled: False

- name: Start and enable firewalld
  become: true
  service:
    name: firewalld
    state: started
    enabled: True

- name: Install EPEL repository
  become: true
  yum: 
    name: epel-release
    state: present

# - name: Add Origin repo
#   become: true
#   yum_repository:
#     name: origin-repo
#     description: Origin RPMs
#     baseurl: https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce_310/27/artifacts/rpms
#     gpgcheck: no
#     enabled: yes
#   notify: yum-clean-metadata

- name: Add Origin repo
  become: true
  yum_repository:
    name: origin-repo
    description: Origin RPMs
    baseurl: https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce_310/27/artifacts/rpms
    gpgcheck: no
    enabled: no
  notify: yum-clean-metadata

####
# - name: Add Origin RPMs repository
#   become: true
#   yum_repository:
#     name: Origin RPMs
#     description: Openshift Origin RPMs
#     baseurl: https://storage.googleapis.com/origin-ci-test/logs/test_branch_origin_extended_conformance_gce/3628/artifacts/rpms

- name: Upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest

# - name: Disable SELinux
#   become: true
#   selinux:
#     state: enforcing
#   notify: Restart server

- name: Install common packages
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - tmux
      - wget 
      - git 
      - net-tools 
      - bind-utils 
      - yum-utils 
      - iptables-services 
      - bridge-utils 
      - bash-completion 
      - kexec-tools 
      - sos 
      - psacct
      - docker-1.13.1
      - glusterfs-fuse
      - centos-release-openshift-origin310
# - name: Uninstall Origin 3.11
#   become: true
#   yum:
#     name: "centos-release-openshift-origin311"
#     state: removed

