---
- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: False
- name: Add EPEL repository
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: Upgrade all packages
  become: true
  yum:
    name: '*'
    state: latest
- name: Install common packages
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - tmux