---
- name: Add EPEL repository
  become: true
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: Upgrade all packages, excluding kernel packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*
- name: Install common packages
  become: true
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - vim
      - tmux